### Shoes API

### Get shoe catalog
GET http://localhost:3003/api/shoes

### Get shoe by shoe_id or item_id
GET http://localhost:3003/api/shoes?shoe_id=1001
###
GET http://localhost:3003/api/shoes?item_id=1027

### Filter shoes by brand
GET http://localhost:3003/api/shoes/brand/Nike
###
GET http://localhost:3003/api/shoes?brand=Nike

### Filter shoes by size
GET http://localhost:3003/api/shoes/size/9
###
GET http://localhost:3003/api/shoes?size=11

### Filter shoes by brand and size
GET http://localhost:3003/api/shoes/brand/Nike/size/9
###
GET http://localhost:3003/api/shoes?brand=Nike&size=9

### Filter shoes by price range
GET http://localhost:3003/api/shoes?price=2000-3000
###
GET http://localhost:3003/api/shoes?price=0-1000
###
GET http://localhost:3003/api/shoes?price=5000-999999

### Combine multiple filters in any order
GET http://localhost:3003/api/shoes?brand=Nike&size=9&color=Black
###
GET http://localhost:3003/api/shoes?color=White&brand=Adidas&size=9
###
GET http://localhost:3003/api/shoes?size=9&color=Black&brand=Under Armour&model=Micro G Valsetz



### Get cart for user
GET http://localhost:3003/api/cart/1000

### Create new cart for user
GET http://localhost:3003/api/cart/1000/create

### Checkout cart for user
POST http://localhost:3003/api/cart/1000/checkout

### Clear cart for user
POST http://localhost:3003/api/cart/1000/clear

### Add shoe to cart
POST http://localhost:3003/api/cart/1000/add/1027

### Add multiple of shoe to cart
POST http://localhost:3003/api/cart/1000/add/1027?item_count=2

### Remove shoe from cart
POST http://localhost:3003/api/cart/1000/remove/1027



### Add shoe to catalog
POST http://localhost:3003/api/shoes
content-type: application/json

{
	"brand": "Under Armour",
	"model": "Micro G Valsetz",
	"price": 2899,
	"variants": [
		{ "color": "Black", "size": 9, "stock_count": 16 },
		{ "color": "Black", "size": 10, "stock_count": 2 },
		{ "color": "Black", "size": 11, "stock_count": 1 },
		{ "color": "Gold", "size": 9, "stock_count": 1 },
		{ "color": "Gold", "size": 10, "stock_count": 1 }
	],
	"photos": [
		{ "color": "Black", "photo_url": "https://i.ibb.co/DGNyqNw/ua-mircogvalsetz-black.webp" },
		{ "color": "Gold", "photo_url": "https://i.ibb.co/g4MHQ9x/ua-mircogvalsetz-gold.webp" }
	]
}